from logging.config import dictConfig

from social_media_api.config import config, DevConfig


def configure_logging() -> None:
    dictConfig(
        {
            "version": 1,
            "disable_existing_loggers": False,
            "formatters": {
                "console": {
                    "class": "logging.Formatter",
                    "datefmt": "%Y-%m-%dT%H:%M:%S",
                    "format": "%(name)s:%(lineno)d - %(message)s",  # %(levelname)s
                },
                "file": {
                    "class": "logging.Formatter",
                    "datefmt": "%Y-%m-%dT%H:%M:%S",
                    "format": (
                        "%(asctime)s.%(msecs)03dZ | "  # Log with time in ISO format
                        "%(levelname)-8s | "  # Show level name always with total of 8 characters to keep them lined up in the terminal
                        "%(name)s:%(lineno)d -  "
                        "%(message)s"
                    ),
                },
            },
            "handlers": {
                "default": {
                    "class": "rich.logging.RichHandler",
                    "level": "DEBUG",
                    "formatter": "console",  # maps to the formatter name
                },
                "rotating_file": {
                    "class": "logging.handlers.RotatingFileHandler",
                    "level": "DEBUG",
                    "formatter": "file",
                    "filename": "social_media_api.log",
                    "maxBytes": 1 * 1024 * 1024,  # 1MB
                    "backupCount": 5,  # Keep only 2 log files, total of 5 MB with this config
                    "encoding": "utf8"
                },
            },
            "loggers": {
                # app's logging config
                "social_media_api": {
                    "handlers": ["default", "rotating_file"],
                    "level": "DEBUG" if isinstance(config, DevConfig) else "INFO",
                    "propagate": False,  # Doesn't send any log generated by storeapi to its parent. I.e. won't send to the root logger.
                },
                # logs from other libraries config
                "uvicorn": {
                    "handlers": ["default", "rotating_file"],
                    "level": "INFO",
                },
                "databases": {"handlers": ["default"], "level": "WARNING"},
                "aiosqlite": {"handlers": ["default"], "level": "WARNING"},
            },
        }
    )
