from logging.config import dictConfig

from social_media_api.config import config, DevConfig


def configure_logging() -> None:
    dictConfig(
        {
            "version": 1,
            "disable_existing_loggers": False,
            "formatters": {
                "console": {
                    "class": "logging.Formatter",
                    "datefmt": "%Y-%m-%dT%H:%M:%S",
                    "format": "%(name)s:%(lineno)d - %(message)s", # %(levelname)s
                }
            },
            "handlers": {
                "default": {
                    "class": "rich.logging.RichHandler",
                    "level": "DEBUG",
                    "formatter": "console", # maps to the formatter name
                }
            },
            "loggers": {
                "social_media_api": {
                    "handlers": ["default"],
                    "level": "DEBUG" if isinstance(config, DevConfig) else "INFO",
                    "propagate": False, # Doesn't send any log generated by storeapi to its parent. I.e. won't send to the root logger.
                }
            },
        }
    )

